version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - docker.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - nestjs-network

  app:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 3001:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - nestjs-network
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nestjs-network:
    driver: bridge
