version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:

    links:

      - postgres:postgres

    container_name: pgadmin

    image: dpage/pgadmin4

    ports:

      - "8080:80"

    volumes:

      - /data/pgadmin:/root/.pgadmin

    env_file:

      - docker.env

    networks:

      - postgres
  dev:
    depends_on:
      - postgres
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - postgres
    env_file:
      - docker.env
    volumes:
      - /data/src/app
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
